# Generated by Django 4.2.4 on 2023-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
