# Generated by Django 4.2.4 on 2023-09-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_appointmentlimit_contact_delete_availabletimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlimit',
            name='limit',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
