# Generated by Django 4.2.4 on 2023-09-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_appointmentlimit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlimit',
            name='limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
