# Generated by Django 4.2.3 on 2023-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_appointmentlimit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
