# Generated by Django 4.2.3 on 2023-09-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_contact_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='limit',
        ),
        migrations.AlterField(
            model_name='appointmentlimit',
            name='limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
